server:
  port: 9060


spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securityDemo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: jongwon
    password: whddnjs121!

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true # templates 디렉토리에 파일이 있는지 없는지 체크
    suffix: .html

#  web:
#    resources:
#      static-locations:

logging:
  level:
    org.springframework.web: trace
