package com.example.demo.mock;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import com.example.demo.common.domain.exception.ResourceNotFoundException;
import com.example.demo.user.domain.User;
import com.example.demo.user.domain.UserStatus;
import com.example.demo.user.service.port.UserRepository;

public class FakeUserRepository implements UserRepository {

	// 사실 테스트는 단일 스레드로 돌아가기 때문에 굳이 멀티 스레드 환경을 고려할 필욘 없다.
	private final AtomicLong autoGeneratedId = new AtomicLong(0);
	private final List<User> data = Collections.synchronizedList(new ArrayList<>());

	@Override
	public User getById(long id) {
		return findById(id).orElseThrow(() -> new ResourceNotFoundException("Users", id));
	}

	@Override
	public Optional<User> findById(long id) {
		return data.stream().filter(item -> item.getId().equals(id)).findAny(); // Stream에서 가장 먼저 탐색되는 요소를 리턴
	}

	@Override
	public Optional<User> findByIdAndStatus(
		long id,
		UserStatus userStatus
	) {
		return data.stream().filter(item -> item.getId().equals(id) && item.getStatus() == userStatus).findAny();
	}

	@Override
	public Optional<User> findByEmailAndStatus(
		String email,
		UserStatus userStatus
	) {
		return data.stream().filter(item -> item.getEmail().equals(email) && item.getStatus() == userStatus).findAny();
	}

	@Override
	public User save(User user) {
		if (user.getId() == null || user.getId() == 0) {
			User newUser = User.builder()
				.id(autoGeneratedId.incrementAndGet())
				.email(user.getEmail())
				.nickname(user.getNickname())
				.address(user.getAddress())
				.certificationCode(user.getCertificationCode())
				.status(user.getStatus())
				.lastLoginAt(user.getLastLoginAt())
				.build();
			data.add(newUser);
			return newUser;
		} else {
			data.removeIf(item -> Objects.equals(item.getId(), user.getId()));
			data.add(user);
			return user;
		}
	}
}
