spring:
  profiles:
    active: local

  batch:
    job:
      names: ${job.name:NONE}


---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:7899/house?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: trip1234

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Seoul
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  batch:
    jdbc:
      initialize-schema: always

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    database: h2
