spring:
  datasource:
    url: jdbc:mysql://localhost:7899/point_management?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: trip1234

  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

